
import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'

import MainContainer from '@/components/containers/main-container'

import QueryProvider from '@/providers/query-provider'

const interSans = Inter({
	variable: '--font-inter-sans',
	subsets: ['latin', 'cyrillic'],
})

const interMono = JetBrains_Mono({
	variable: '--font-inter-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${interSans.variable} ${interMono.variable} antialiased box-border h-full m-0`}
			>
				<QueryProvider>
					<MainContainer>{children}</MainContainer>
				</QueryProvider>
			</body>
		</html>
	)
}
