// TODO:
// 	Бесконечные маршруты по папкам наверно не будут работать
// 	Кривые папки в Folders
// Реализовать Popup

import { Header } from '@/components/elements/header/Header'
import { Sidebar } from '@/components/elements/sidebar/Sidebar'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import DragAndDropModal from '@/components/ui/dropzone/dropzone'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased box-border h-full m-0`}
			>
				<main className='h-screen flex'>
					{/** Sidebar  */}
					<Sidebar />
					<section className='flex-1 overflow-auto p-layout'>
						<Header />
						<div className='flex  flex-col'>{children}</div>
						<DragAndDropModal/>
					</section>
				</main>
			</body>
		</html>
	)
}
