// TODO:
// 	Бесконечные маршруты по папкам наверно не будут работать
// 	Кривые папки в Folders
// Реализовать Popup

import { Header } from '@/components/elements/header/Header'
import { Sidebar } from '@/components/elements/sidebar/Sidebar'
import type { Metadata } from 'next'
import { Inter, JetBrains_Mono } from 'next/font/google'
import './globals.css'
import DragAndDropModal from '@/components/ui/drag-drop/drag-drop'
import Upload from '@/components/elements/upload/upload'
import CreateFolder from '@/components/elements/create-folder/create-folder'

const interSans = Inter({
	variable: '--font-inter-sans',
	subsets: ['latin', 'cyrillic'], // Добавь cyrillic, если нужен русский язык
})

const interMono = JetBrains_Mono({
	variable: '--font-inter-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body
				className={`${interSans.variable} ${interMono.variable} antialiased box-border h-full m-0`}
			>
				<main className='h-screen flex'>
					{/** Sidebar  */}
					<Sidebar />
					<section className='flex-1 overflow-auto p-layout'>
						<Header />
						<div className='flex  flex-col'>{children}</div>
						<Upload />
						<CreateFolder />
					</section>
				</main>
			</body>
		</html>
	)
}
